### ISSUE TITLE
Pflichtenheft - Produktdaten

### ISSUE THREAD

**Issue by Alligatooo** [vlle1/dokumente-earablesKIT#9]

**Comment by vlle1** [comment]
@Alligatooo  zu PD040: ich dachte wir speichern keine Bestenlisten, sondern einfach linear alle Vorgänge? oder hab ich das falsch im Kopf?

**Comment by vlle1** [comment]
wüde vorschlagen wir klären das mit dem punkt danach beim nächsten treffen, bist du ansonsten fertig denke ich d.h. ich hake das jetzt mal ab (habe es durchgeschaut / "gereviewed"). kannst den issue ja wieder auf machen wenn du nicht zufrieden bist.
